[package]
name = "ruxum"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.45.1", features = ["full"] }

#Axum
axum = "0.6.0"

#serde
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"


[dev-dependencies]
anyhow = "1"
httpc-test = "0.1.1"