[package]
name = "ruxum"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
tokio = { version = "1.45.1", features = ["full"] }

serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
anyhow = "1.0.98"
