[package]
name = "ruxum"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.45.1", features = ["full"] }

#Axum
axum = "0.8.4"

#serde
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"


[dev-dependencies]
anyhow = "1.0.98"
httpc-test = "0.1.10"